#!/usr/bin/perl 

for ($i=0;$i<=$#ARGV;$i++){
    if($ARGV[$i] eq "-gwas"){
        $gwas_file = $ARGV[++$i];
        next;	
    }

    if($ARGV[$i] eq "-eqtl"){
        $eqtl_file = $ARGV[++$i];
        next;	
    }


}


print STDERR "Processing eQTL data ...\n";



open FILE, "$eqtl_file";
while(<FILE>){
    next if $_ !~ /\d/;
    my @data = split /\s+/, $_;
    shift @data until $data[0]=~/^\S/;
    $pip{$data[0]} = $data[1];
}

print STDERR "Read in GWAS ...\n";
open FILE, "zcat $gwas_file | ";
while(<FILE>){
    chomp;
    next if $_ !~ /\d/;
    my @data = split /\s+/, $_;
    shift @data until $data[0]=~/^\S/;
    printf "$_  %7.3e\n", $pip{$data[0]};
}


